<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <style type="text/css">
        body {
            font-family: 'Arial', sans-serif;
            font-size   : 12px;
            color       : #444;
            line-height : 16px;
        }
        a, a:visited {
            color : #2972A2;
        }
        a:hover {
            color : #6ed347;
        }
        h2{
          color: #2972A2;
        }
   	</style>
</head>
<body>
  <header>
      <h1>{{title}}</h1>
  </header>
  <hr/>
  <h2>{{content}}</h2>
</body>
</html>
