<!DOCTYPE html>
<html>
  <head>
    <title>#title#</title>
  
    <meta charset="utf-8"/>
    <meta name="description" content="#description#"/>
    <meta name="keywords" content="#keywords#"/>
    <meta name="language" content="#lang#"/>
    <meta name="author" content="#author#"/>
  
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=0"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
  
    <link rel="shortcut icon" href="../favicon.ico"/>
    <link href='js/syntax/styles/shCore.css' rel='stylesheet' type='text/css'/>   
    <link href='js/syntax/styles/shThemeDefault.css' rel='stylesheet' type='text/css'/>   
    <link href='css/base_style.css' rel='stylesheet' type='text/css'/>    
    <script src="js/modernizr.custom.js"></script>
    <script src="js/load.js"></script>

  </head>
  
  <body>
    <section class="presentation">
      <section class="slides">
        #slides#
      </section>
    </section>
  </body>
</html>
